name: terraform build
on:
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ec2
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install terraform
        uses: hashicorp/setup-terraform@v3
      - name: init
        run: terraform init
      - name: validate
        run: terraform validate
      - name: fmt
        run: terraform fmt -recursive
      - name: plan
        run: terraform plan
##if: github.event_name == 'workflow_dispatch'##
